version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=asr_labeling
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d asr_labeling"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=asr_labeling
      - POSTGRES_HOST=db
      - SECRET_KEY=your-secret-key-here
      - AUDIO_UPLOAD_FOLDER=/data/audio_files
    volumes:
      - ./data/audio_files:/data/audio_files
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    volumes:
      - ./data/audio_files:/data/audio_files

volumes:
  postgres_data: